repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
-   repo: https://github.com/yelp/detect-secrets
    rev: v0.14.2
    hooks:
    -   id: detect-secrets
